version: '3.3'
services:
    webissues:
        ports:
            - '80:80'
        volumes:
            - './webissues-server-1.1.2:/var/www/html'
            - './data:/var/www/html/data'
        image: 'nikinname/webissues:prod'
    db:
        image: mariadb:10.5.9
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: LaMiaSegretissimaPassword
          MYSQL_DATABASE: webissues
          MYSQL_USER: webissues
          MYSQL_PASSWORD: webissues
        volumes:
            - './dbdata:/var/lib/mysql'
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - UPLOAD_LIMIT=300M
